services:
  - type: web
    name: eligible-stem-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: ADMIN_IDS
        sync: false  # User must input this in Dashboard
      - key: SHEET_ID
        sync: false  # User must input this in Dashboard
      - key: GOOGLE_CREDENTIALS
        sync: false  # User must input this in Dashboard
